### ISSUE TITLE
Separate config file support from config values

### ISSUE THREAD

**Issue by eschaton** [dseagrav/ld#10]
Right now the config file support directly integrates the configuration variables and their types. The config file/variable handling should be independent, so:

- variables could have default values when unset
- subsystems could specify their variables & default values in the subsystem initialization
- config values could be provided via multiple files overriding each other (e.g. `/opt/ld/share/ld.conf` for site-wide config and `~/ld.conf` for per-user config)
- config values could be overridden on the command line in a standard way

**Comment by dseagrav** [comment]
The YAML config does this.
