### ISSUE TITLE
config.status: error: cannot find input file: `tools/Makefile.in'

### ISSUE THREAD

**Issue by bictorv** [dseagrav/ld#28]
On MacOS 10.14.4, after "autoconf -f", the following seems to indicate a missing file in the repo:

```
$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
....
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: error: cannot find input file: `tools/Makefile.in'
```

**Comment by ams** [comment]
What happens if you just try running automake?  That should generate tools/Makefile.in.  The configure.ac file looks correct.

**Comment by bictorv** [comment]
Of course.

**Comment by ams** [comment]
FWIW, always run autoreconf instead of automake or autoconf separately.  It will do the right thing.

**Comment by bictorv** [comment]
Thanks! For some reason I ran autoconf, instead of autoreconf that I used previously. Part of the cause of the confusion, I think.
At some point I'll try to understand all this properly (and use it to configure cbridge).
