### ISSUE TITLE
README.md instructions correction for bogodyne 

### ISSUE THREAD

**Issue by noahfriedman** [dseagrav/ld#33]
It looks like the initial name of the machine when using the new tape images should be "LISPM-A" rather than "LAMBDA-A".  If you use the latter, the machine gets no chaosnet address and refers to itself as AMNESIAC.

Edit: since these and other details of installation may become increasingly more dependent on the system releases themselves, perhaps those notes should move to that distribution.  I didn't want to propose a PR for this until there was a public repository for it, though.

**Comment by shrzen** [comment]
I am in no way affiliated with this project. I just happened to see this issue earlier, and since I've made the same error of using the wrong hostname I decided to make the PR.

**Comment by dseagrav** [comment]
Merged fix from pull request
